kernel.unprivileged_userns_clone=1
user.max_user_namespaces=28633
kernel.keys.maxkeys=20000
kernel.keys.maxbytes=2000000
fs.inotify.max_user_instances=1024
fs.inotify.max_user_watches=1048576
fs.aio-max-nr=1048576
net.ipv4.ip_forward=1
net.ipv6.conf.all.forwarding=1
-net.bridge.bridge-nf-call-iptables=1
-net.bridge.bridge-nf-call-ip6tables=1
-net.bridge.bridge-nf-call-arptables=0
