config:
  name: rockchip64-6.18
  kind: kernel
  type: mainline
  branch: linux-6.18.y

  dts-directories:
    - { source: "dt", target: "arch/arm64/boot/dts/rockchip" }

  auto-patch-dt-makefile:
    - { directory: "arch/arm64/boot/dts/rockchip", config-var: "CONFIG_ARCH_ROCKCHIP" }
